using System;
using ToolGood.Words;

namespace Hackus_Mail_Checker_Reforged.Net.Mail.Utilities
{
	// Token: 0x02000102 RID: 258
	public static class ArgumentExtensions
	{
		// Token: 0x060007E3 RID: 2019 RVA: 0x00030140 File Offset: 0x0002E340
		static ArgumentExtensions()
		{
			ArgumentExtensions._serverDisabledArguments.SetKeywords(new string[]
			{
				"pop3 access disabled",
				"login disabled for this user",
				"please modify the password",
				"server license expired",
				"you are not pop3-enabled user",
				"pop access disabled",
				"imap access disabled",
				"pop3 disabled",
				"pop disabled",
				"imap disabled",
				"pop3 service disabled",
				"pop service disabled",
				"imap service disabled",
				"not pop3 user",
				"not pop user",
				"user is locked",
				"child crashed",
				"not imap user",
				"pop3 server has unexpectedly disconnected",
				"pop server has unexpectedly disconnected",
				"imap server has unexpectedly disconnected",
				"command syntax error",
				"missing required argument to login",
				"system error",
				"server shutdown",
				"deactivated",
				"suspend",
				"access not allowed",
				"temporary error",
				"clock skew detected",
				"quarantine",
				"unable to lock maildrop",
				"unknown command",
				"login using a browser",
				"your account is not allowed to use the pop3 service",
				"your account is not allowed to use the pop service",
				"your account is not allowed to use the imap service",
				"user has locked",
				"pop3 nosupport",
				"imap nosupport",
				"????",
				"err.login.usrstatus1",
				"err.login.usrstatus2",
				"err.login.usrstatus5",
				"service disabled",
				"8bit",
				"service temporarily unavailable",
				"internal server error",
				"cannot connect to axigen",
				"syntax error",
				"cmmand is not valid in this state",
				"server error",
				"not enabled for pop",
				"not enabled for pop3",
				"db error",
				"no mailbox",
				"disabled pop3 access",
				"disabled pop access",
				"disabled imap access",
				"please change password",
				"can not connect to e-mail server",
				"does not have pop email access",
				"err.login.passchange",
				"account is frozen",
				"mailbox locked",
				"over quota",
				"cannot connect to imap server",
				"cannot connect to pop3 server",
				"cannot connect to pop server",
				"authorized code",
				"twoje konto stracilo waznosc dnia",
				"error in server configuration",
				"application-specific password",
				"error creating table",
				"unsupported authentication mechanism",
				"altpass",
				"cannot connect to the server",
				"mailbox unavailable",
				"account is either disabled",
				"pop operation is not allowed for this user",
				"account disabled",
				"not pop3 permited",
				"not pop permited",
				"not imap permited",
				"enable pop3 access",
				"enable pop access",
				"enable imap access",
				"pop access disabled",
				"imap access disabled",
				"nincs",
				"user disabled",
				"required new password",
				"password has been leaked",
				"please log in on the webmail"
			});
			ArgumentExtensions._accountBlockedArguments.SetKeywords(new string[]
			{
				"try again",
				"block",
				"captcha",
				"spamhaus.org",
				"rate limit",
				"access from your network is temporarily disabled",
				"prevention active",
				"html",
				" rbl",
				"timeout",
				"try later",
				"banned",
				"too many",
				"closed",
				"inactivity",
				"exceeded",
				"inactive",
				"too long",
				"ip",
				"mailbox in use",
				"blacklisted",
				"cannotconnecttoidentd",
				"time out",
				"ipdeny",
				"connectionrefused",
				"typenotsupported",
				"hostunreachable",
				"networkunreachable",
				"connectionnotallowedbyruleset",
				"ttlexpired",
				"unknownerror",
				"noacceptablemethods",
				"server terminating connection",
				"commandnotsupported",
				"busy",
				"in-use",
				"rejecteddifferentidentd",
				"unknown error",
				"reject imap4 connections",
				"reject imap connections",
				"concidered spam",
				"collision",
				"unable to find account",
				"disconnected",
				"disconnecting",
				"autologout",
				"try your connection",
				"sprobuj jutro",
				"refused",
				"http/1.1"
			});
			ArgumentExtensions._invalidArguments.SetKeywords(new string[]
			{
				" no ",
				"account or password is error",
				"login failed",
				"not known",
				"密码错误",
				"bad user/password",
				"invalid",
				"id login or password., fail_code",
				"username does not exist",
				"authfail",
				"error in processing",
				"internal error",
				"invalid auth",
				"login failure",
				"failure",
				"password error",
				"rejectedorfailed",
				"failed",
				"incorrect password or account name",
				"login not allowed",
				"username or password is incorrect",
				"nebyl autorizovan",
				"not accepted",
				"access denied",
				"user does not exist",
				"clientbug",
				"wrong",
				"unable to log on",
				"incorrect",
				"bad login",
				"no such user or password",
				"bad password or unknown username",
				"account is temporarily unavailable.",
				"do not match",
				"unexpected",
				"command argument error. 12",
				"user could not be routed",
				"user not found",
				"expected end of data instead of",
				"no such user",
				"bad command error",
				"bad expected end of data instead",
				"bad username/password",
				"string instead of",
				"not authenticated",
				"unknown(or unapproved) user",
				"auth limit",
				"err.login.passerr",
				"err.login.usernotexist",
				"user not exist",
				"security violation",
				"user expired",
				"auth error",
				"login fail",
				"벻",
				"not the password",
				"authentication error - 0402",
				"unknown user account",
				"can't call method \"passwd\"",
				"unauthorized",
				"unable to log",
				"account has been moved",
				"doesn't exist",
				"check user and password",
				"not allowed in strings",
				"nieprawidlowe haslo",
				"user-id error",
				"user not local",
				"unable user",
				"not know this user",
				"exceeds maximum permitted size",
				"user unknown",
				"unknown user",
				"unrecognised",
				"user password",
				"user disabled",
				"login fehlgeschlagen",
				"policy"
			});
		}

		// Token: 0x060007E4 RID: 2020 RVA: 0x0000AD9D File Offset: 0x00008F9D
		public static bool IsServerDisabled(this MailException exception)
		{
			return exception != null && exception.Message != null && ArgumentExtensions._serverDisabledArguments.ContainsAny(exception.Message.ToLower());
		}

		// Token: 0x060007E5 RID: 2021 RVA: 0x0000ADC1 File Offset: 0x00008FC1
		public static bool IsBlocked(this MailException exception)
		{
			return exception != null && exception.Message != null && ArgumentExtensions._accountBlockedArguments.ContainsAny(exception.Message.ToLower());
		}

		// Token: 0x060007E6 RID: 2022 RVA: 0x0000ADE5 File Offset: 0x00008FE5
		public static bool IsServerDisabled(this string message)
		{
			return !string.IsNullOrEmpty(message) && ArgumentExtensions._serverDisabledArguments.ContainsAny(message.ToLower());
		}

		// Token: 0x040003F7 RID: 1015
		private static StringSearch _serverDisabledArguments = new StringSearch();

		// Token: 0x040003F8 RID: 1016
		private static StringSearch _accountBlockedArguments = new StringSearch();

		// Token: 0x040003F9 RID: 1017
		private static StringSearch _invalidArguments = new StringSearch();
	}
}
